name: expensesmanager
services:
  web:
    platform: "linux/amd64"
    build: .
    image: ${DOCKERHUB_REGISTRY}/expensesmanager
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=azure-sql-edge;Initial Catalog=Expenses;User Id=sa;Password='Pass@123';Trust Server Certificate=True;"
    ports:
      - 80:8080

  db:
    container_name: azure-sql-edge
    image: mcr.microsoft.com/azure-sql-edge
    ports:
        - 1433:1433
    restart: always
    volumes: 
        - azure-sql-edge-data:/var/opt/mssql
    environment:
        MSSQL_SA_PASSWORD: "Pass@123"
        ACCEPT_EULA: "Y"
volumes:
    azure-sql-edge-data: